config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
  	collection do
  		get :erase
  	end
  end
  root "tasks#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    def self.search(term)
    	if term && "#{term}" != ' '
    		before_split = "#{term}"
    		stop_words = [
    			"who ", "where ", "how ", "many ", "is", "do ", "my ", "i ",
    			"are ", "you ", "this "]
    		stop_words.each do |p|
    			term.gsub!(/#{p}/, '')
    		end
    		#key words that my user base will search for (generic search)
    		#key_words = [
    		#	"account ", "login ", "signup ", "pricing", "price",
    		#	"value", "much", "cancel", "credit card", "email",
    		#	"delete", "create", "payment", "hours", "reset",
    		#	"password"]

    		# if even after split stop_words the size of term was greater than
    		# 2 and has a key_word from my array, then and only then i'll
    		# save in the DB
    		if(term.split.size >= 2 )
    			#if(key_words.any?{ |word| term.include?(word)})
    				$redis.incr before_split.split.map(&:capitalize).join(' ')
    			#end
    		end
   		    # whotewise will return nothing and will not save search
            where('name LIKE ?', "%#{term}%")
    	else
    		all
    	end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
      # if term search is valid, capitalize first letter from each word
      if(params[:term] != nil)
        @tasks = Task.search(params[:term].downcase)
      else
        # else :term is whitespace or null returns all tasks
        @tasks = Task.search(params[:term])
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end


  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LCARS // Rodrigo Andrade</title>
    <link rel="icon" type="image/png" href="https://cdn4.iconfinder.com/data/icons/office-time/512/3-128.png">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class:"capitalizeText" %>
  </div>

  <div class="actions">
  <button submit_tag="Create">Create</button>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="header">
<h1>LCARS</h1>
<%= javascript_tag do %>
  var array = [];
  <% @tasks.each do |task| %>
    array.push("<%= task.name %>")
  <% end %>
  var sortKeys = function(a, b){return b-a};
<% end %>
<div class="search">
<%= form_tag tasks_path, method: 'get' do %>
  <div class="searchField">
  <%= text_field_tag :term, params[:term] , class: 'input is-large typeahead'%>
  </div>
  <div class="searchButton">
  <button submit_tag = "Search" class="button" id="send">Search</button>
  </div>
<% end %>
</div>
</div>
<div class="analytics">
<div class="tasksCreated">
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th colspan="1"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name.capitalize %></td>
        <td><%= link_to '', task, class: "fa fa-trash-o", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div id="newTask">
<%= link_to 'New Task', new_task_path, class: "button is-small is-warning is-outlined" %>
</div>
</div>


<div class="mostSearchedQuestion">
<table id="orderSearch" class="display">
  <thead>
    <tr>
      <th>Most Searched Question</th>
      <th colspan="1">How Many ?</th>
    </tr>
  </thead>

<tbody id="searched">
<% $redis.keys.each do |key| %>
  <tr>
    <td><%= key %></td>
    <td><%= $redis.get(key) %></td>
  </tr>
  <% end %>
</tbody>
</table>
<button type="button" id="eraseRedis" class="button is-danger" >Clear All Analytics</button>
</div>

</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>